[technote]
id = "SITCOMTN-177"
series_id = "SITCOMTN"
canonical_url = "https://sitcomtn-177.lsst.io"
github_url = "https://github.com/lsst-sitcom/sitcomtn-177"
github_default_branch = "main"
date_created = 2026-01-14T22:32:50Z
organization.name = "NSF-DOE Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "David"
name.family = "Sanmartim"
internal_id = "sanmartimd"
orcid = "https://orcid.org/0000-0002-9238-9521"
[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory"
internal_id = "RubinObsC"
address = "La Serena"
